"""job attempt count and failed status

Revision ID: 48d7dae5df2e
Revises: 53583cb94875
Create Date: 2026-07-21 19:59:18.036852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48d7dae5df2e'
down_revision: Union[str, Sequence[str], None] = '53583cb94875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'jobs', sa.Column('attempt_count', sa.Integer(), nullable=False, server_default='0')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'attempt_count')
    # ### end Alembic commands ###
