"""document classification confidence

Revision ID: 53583cb94875
Revises: de9a04b19af1
Create Date: 2026-07-21 19:31:45.651332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53583cb94875'
down_revision: Union[str, Sequence[str], None] = 'de9a04b19af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('classification_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'classification_confidence')
    # ### end Alembic commands ###
