#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
TOTAL_MINUTES=20

# Observations land here, not in the project .env — this wizard captures facts
# about a third-party UI, not configuration the app reads.
ENV_FILE="${ENV_FILE:-$HOME/document-intelligence-reference/invoices/demofiok-notes.env}"
mkdir -p "$(dirname "$ENV_FILE")"

banner "Számlázz.hu demófiók — issue a synthetic invoice (#68)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Find the demófiók" 3
say "Goal: reach Számlázz.hu's public demo account. No registration, no email,"
say "no tax number — it exists precisely so nobody has to sign up."
open_url "https://www.szamlazz.hu/"
step "On the homepage, find the demo entry point. It is usually 'Kipróbálom'"
step "or 'Demó'. If a login is asked for, the credentials are demo / demo."
warn "The homepage is JavaScript-rendered, so the exact link text could not be"
warn "verified in advance. Navigate by eye — do not trust a memorised URL."
note "Source: tudastar.szamlazz.hu/gyik/mire-hasznalhatom-a-demofiokot"
ask DEMO_URL "Paste the URL you actually landed on:"
write_env DEMO_URL "$DEMO_URL"
note "Recorded so the next run can skip the hunt."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Gate — is the issuer a dummy?" 2
warn "Check this BEFORE typing anything. It is the whole reason we chose the"
warn "demófiók over the tesztfiók."
say "The tesztfiók was rejected because its issuer tax number is real and"
say "immutable ('A számlakibocsátó saját adatai és adószáma nem módosítható')."
say "The demófiók should instead show a made-up issuer belonging to nobody."
step "Open the invoice-issuing screen and look at the seller / issuer block."
step "Read its company name, address and adószám."
ask ISSUER_NAME "What company name does the issuer block show?"
ask ISSUER_TAX "What adószám does it show? (type 'none' if blank)"
write_env ISSUER_NAME "$ISSUER_NAME"
write_env ISSUER_TAX "$ISSUER_TAX"
if ! confirm "Is that issuer clearly a placeholder, and NOT a real company you recognise?"; then
  warn "Stop here. Do not issue anything."
  warn "A real issuer means the PDF cannot be committed as synthetic."
  warn "Report this on issue #68 and hand the decision back to map #65."
  exit 1
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Enter the buyer" 3
say "The buyer is fully synthetic. It mirrors the committed golden fixture"
say "'invoice/happy_path' so the two documents can be compared directly —"
say "same buyer, two renderings."
warn "The adószám below carries a DELIBERATELY INVALID check digit (convention 8)."
warn "Do not 'correct' it. If the form rejects it, say so at the end."
say ""
say "  Név:      Zöldövezet Építőipari Kft."
say "  Adószám:  35740918-2-05"
say "  Cím:      3529 Miskolc, Tűzköves utca 7/B"
say ""
step "Type those three values into the buyer (Vevő) fields."
pause "Entered? Press Enter."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Enter the invoice header and lines" 5
say "Header:"
say "  Fizetési mód:      átutalás"
say "  Pénznem:           Ft"
say "  Kiállítás kelte:   today"
say "  Teljesítés kelte:  today"
say "  Fizetési határidő: today + 14 days"
say ""
say "Two line items, both at 27% ÁFA:"
say "  1. Fenyő palló      — 250 fm    @ 409,40 Ft"
say "  2. Asztalosmunka    — 12,5 óra  @ 5 772,00 Ft"
say ""
note "The golden fixture's other two lines (fordított adózás, TAM) are omitted"
note "on purpose. This PDF is a LAYOUT reference; the synthetic fixtures already"
note "cover the schema edge cases, and a #start-package UI may not offer those"
note "markings at all."
step "Enter the header fields and both line items."
step "Let the provider compute the totals — do not override its arithmetic."
pause "Entered? Press Enter."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Issue and download" 3
step "Issue the invoice (Számla kiállítása)."
step "Download the resulting PDF."
note "The demófiók is a SHARED, PUBLIC sandbox and is wiped at end of day."
note "Everything above is synthetic, so that is fine — but download it now."
pause "PDF downloaded? Press Enter."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Gate — check the PDF itself" 2
warn "Verify on the PDF, not on the screen you typed into."
step "Open the downloaded PDF."
step "Look for a MINTA watermark."
step "Re-read the issuer block on the PDF and confirm it matches stage 2."
ask WATERMARK "Is a MINTA watermark visible? (yes / no)"
write_env WATERMARK "$WATERMARK"
if [[ "$WATERMARK" != "yes" ]]; then
  warn "No watermark. That is not fatal, but it is a finding:"
  warn "the research claimed one, sourced only from a blog post, not the FAQ."
  warn "Record it on #68 — convention 3's README must then carry the whole"
  warn "'this is synthetic' claim on its own."
fi
if ! confirm "Does the PDF's issuer still look like a placeholder?"; then
  warn "Stop. Do not keep this PDF. Report on #68."
  exit 1
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Save it outside the repo" 2
say "Map #65 has not yet decided whether a provider PDF can be committed,"
say "so this lands outside the working tree — the same treatment docs/prado/ gets."
DEFAULT_DIR="$HOME/document-intelligence-reference/invoices"
mkdir -p "$DEFAULT_DIR"
say ""
say "  Suggested: $DEFAULT_DIR/szamlazz-demofiok.pdf"
say ""
step "Move the downloaded PDF there."
ask PDF_PATH "Where did you put it? (full path)"
write_env PDF_PATH "$PDF_PATH"
if [[ -f "$PDF_PATH" ]]; then
  note "Confirmed: file exists."
else
  warn "No file at that path — check it before closing #68."
fi
ask SURPRISES "Anything on the PDF the layout research did not predict? (one line, or 'none')"
write_env SURPRISES "$SURPRISES"

finish
